### PR TITLE
feat(nodejq): add more request options and powerful jq commands

### PR DESCRIPTION
**Pull request by qistoph**
This PR adds:
- transparent parameters for `request` (e.g. `method: "POST"`)
- jq processing of incoming data
- multiple MMM-json instances support

This allows me, and others of course, to do really powerful JSON conversions.

I will be using it to display next episodes per TV show available on my [Kodi](https://kodi.tv). Example below.

**NOTE**: The sample provided in the README is dependent on my [PR for node-jq](https://github.com/sanack/node-jq/pull/365).

## Kodi example

```
{
  module: "MMM-json",
  position: "bottom_left",
  header: "TV Shows",
  config: {
    url: "http://user:password@kodi/jsonrpc",
    request: {
      method: "POST",
      json: {
        "jsonrpc":"2.0",
        "method": "VideoLibrary.GetEpisodes",
        "id": "neweps",
        "params": {
          "properties": [
            "title",
            "playcount",
            "showtitle",
            "season",
            "episode"
          ],
          "filter": {
            "field": "playcount",
            "operator": "is",
            "value": "0"
          },
          "sort": {
            "order": "ascending",
            "method": "tvshowtitle",
            "ignorearticle": true
          }
        }
      }
    }
    jq: ".result.episodes | [group_by(.showtitle)[] | {(.[0].showtitle): .[0].label}] | add"
  }
}
```

This uses the Kodi JSON-RPC to search for unwatched episodes. The result (see below) is converted using a jq command to select only the last episode per show and convert it to a JSON object. Which I don't think would be possible with JSONPath.

```
{
  "id": "neweps",
  "jsonrpc": "2.0",
  "result": {
    "episodes": [
      {
        "episode": 1,
        "episodeid": 3715,
        "label": "9x01. Episode 1",
        "playcount": 0,
        "season": 9,
        "showtitle": "Call the Midwife",
        "title": "Episode 1"
      },
      {
        "episode": 2,
        ...
        "showtitle": "Call the Midwife",
        ...
      }
      ...
      {
        "episode": 8,
        "episodeid": 3890,
        "label": "3x08. Crisis Theory",
        "playcount": 0,
        "season": 3,
        "showtitle": "Westworld",
        "title": "Crisis Theory"
      }
    ],
    "limits": {
      "end": 100,
      "start": 0,
      "total": 100
    }
  }
}
```

```
{
  "Call the Midwife": "9x01. Episode 1",
  "Westworld": "2x01. Journey into Night"
}
```

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Nice! I will have a look in the evening.

**Comment by qistoph** [comment]
Had been testing this on a VM and just now found out there is no jq readily available for ARM. Which makes node-jq not work on a Pi...

So this is going to take some more work.

I'll keep you posted

**Comment by DanielHabenicht** [comment]
Maybe use https://github.com/FGRibreau/jq.node ?

**Comment by qistoph** [comment]
jq.node is indeed quite a nice alternative.
I wasn't familiar with it, but it seems to integrate into NodeJS a lot better than jq.

PR updated to use jq.node.

**Pull request merged**
